### ISSUE TITLE
Missing LICENSE.TXT once installed

### ISSUE THREAD

**Issue by mattip** [conda-forge/wheel-feedstock#43]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Looking at the installed info in `miniconda3/envs/pytorch-test/lib/python3.8/site-packages/wheel-0.36.2-py3.6.egg-info`, I do not see the LICENSE.TXT file. It seems something is off somewhere? 
```
$ ls ~/miniconda3/envs/wheel-test/lib/python3.8/site-packages/wheel-0.36.2-py3.6.egg-info/
dependency_links.txt  entry_points.txt  not-zip-safe  
PKG-INFO  requires.txt  SOURCES.txt  top_level.txt
```
The feedstock is pulling `https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz` where `version` is `0.36.2`. When I download that, I see the `LICENSE.txt` in the top level.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/matti/miniconda3/envs/wheel-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.1.0               hc902ee8_6    conda-forge
libgomp                   11.1.0               hc902ee8_6    conda-forge
libstdcxx-ng              11.1.0               h56837e0_6    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.2.2             pyhd8ed1ab_0    conda-forge
python                    3.8.10          h49503c6_1_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
 conda info

     active environment : wheel-test
    active env location : /home/matti/miniconda3/envs/wheel-test
            shell level : 2
       user config file : /home/matti/.condarc
 populated config files : /home/matti/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.8.8.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/matti/miniconda3  (writable)
      conda av data dir : /home/matti/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
          package cache : /home/matti/miniconda3/pkgs
                          /home/matti/.conda/pkgs
       envs directories : /home/matti/miniconda3/envs
                          /home/matti/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.8.8 Linux/5.4.0-80-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/matti/.netrc
           offline mode : False

```
</details>

**Comment by mattip** [comment]
xref @milos-korenciak who pointed this out

**Comment by ocefpaf** [comment]
See the `/info/licenses/` in the conda package. We can remove the hardcoded license now though, when we first created the package the upstream tarball did not had the license file.

**Comment by mattip** [comment]
> See the /info/licenses/ in the conda package

Ahh, I see, this ends up in `~/miniconda3/pkgs/wheel-0.36.2-pyhd3eb1b0_0/info/licenses/LICENSE.txt` on my machine. Thanks. @milos-korenciak does that answer your question?

**Comment by milos-korenciak** [comment]
@mattip I understand now how things are working.
Anyway - it should be briliant to have the license files also in the package metadata in appropriate .../site-packages/wheel-0.36.2-py3.6.egg-info/LICENSE[.txt] file, if it is not a problem. The simpler way to find the package license, the better / more transparent license checking & enforcement. (Ultra annoying job in my scale!)

**Comment by mattip** [comment]
It seems conda has settled on putting the licenses in `pkg`, and I could not find a single package that puts it in `*egg-info`, so that would be a non-standard request.

I found license files in
`pkgs/*/info/licenses/*`  (most common),
`pkgs/*/info/LICENSE*`

Now I am going a bit off topic, but since I checked ...

In over 1000 packages in `pkgs/*`, I found  license files following the recipe above for the vast majority. The ones missing licenses as far as I could tell (I am not a lawyer, maybe I have older versions, do meta-packages need license files?) were:

async_generator
blas-1.0-mkl (blas-2.17-openblas did have a LICENSE.txt)
c-compiler
clyent
cxx-compiler
fortran-compiler
gcc_impl_linux
gfortran_impl_linux
gst-pluginss-base
gstreamer
gxx_impl_linux
isodate
lib-gcc-devel_linux
_libgcc_mutex
libgcc-ng-11
libgcc-ng-9
libgcc-ng
libgdal
libgfortran4
libgfortran5
libgfortran-ng
libgomp
libpq12
libpq13
libgfortran4
libstdcxx-devel_linux
libstdcxx-ng
libxcb-1.14
lumen
multipledispatch
pandas-bokeh
parquet-cpp
postgresql-13
ptyprocess
sqlite-3.*
_tflow_select

<details>

To see what packages I have
`ls -d pkgs/*/info > /tmp/packages`
To find all the license files
```
ls -d pkgs/*/info/licenses > /tmp/licenses
ls -d pkgs/*/info/LIC* >> /tmp/licenses
sort /tmp/licenses > /tmp/licenses1
```

Then I did `vimdiff /tmp/licenses1 /tmp/packages`
and went through the diff, adding blank lines in `/tmp/licenses1` for each bad match.
</details>

**Comment by milos-korenciak** [comment]
It is very fine if even metapackage has license properly set. It makes clear and firm the checking + license enforcement.

I am not lawyer, but I not to be one when I see (BSD, MIT, ...) license saying "this license MUST be added in any code distribution" and the author does not add it to the (pure Py) package... Anyway I do "happy" "fetch work" for the license checking.

Now I know for conda env there is different way to find metadata compared to pip. Anyway, I need to use `pip install` to get proprietary packages, so I need to join the two approaches together.

**Comment by jakirkham** [comment]
Sounds like there was nothing to do here. Closing this out. Though please feel free to reopen if I've misunderstood. Thanks!
